FROM python:3.7

RUN apt update && \
  apt install -y --no-install-recommends \
  libgl-dev libgl1-mesa-glx libsm6 xvfb && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*

RUN  python3 -m pip install pip -U && \
  python3 -m pip install vtk==8.1.2 pyvirtualdisplay && \
  git clone https://github.com/MICA-MNI/ENIGMA.git && \
  cd ENIGMA && \
  python3 -m pip install . -r requirements.txt 

COPY ./test.py /tmp/
COPY ./display.py /tmp/

RUN python3 /tmp/test.py